# Generated by Django 4.2.5 on 2023-11-09 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatbotMessage',
        ),
    ]
